### ISSUE TITLE
Add CDN and stylesheet links to HTML file

### ISSUE THREAD

**Issue by nabeek** [nabeek/Earthquake-Now#2]
Stylesheets-
Bulma: https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css
Fontawesome: https://use.fontawesome.com/releases/v5.8.1/css/all.css
Local CSS

Scripts-
jQuery: https://code.jquery.com/jquery-3.4.1.min.js
Moment JS: https://momentjs.com/downloads/moment.min.js
Local JS

**Comment by shiftymitch** [comment]
Issue completed, #8
