### ISSUE TITLE
Define parameters for distance from searched area

### ISSUE THREAD

**Issue by shiftymitch** [nabeek/Earthquake-Now#25]
USGS - circle 
https://earthquake.usgs.gov/fdsnws/event/1/

**Comment by shiftymitch** [comment]
maybe use a dropdown selector with distance options

**Comment by nvalline** [comment]
Define how far back in time to display data

**Comment by nabeek** [comment]
Let's hardcode our var maxRadiuskm to 160 (equates to 100mi)

**Comment by shiftymitch** [comment]
Closed issue, #71
