### ISSUE TITLE
Build web page in HTML based on Figma design

### ISSUE THREAD

**Issue by nabeek** [nabeek/Earthquake-Now#5]
Focus on mobile layout first, then we'll adapt the design for full-page layout

[Earthquake Now.pdf](https://github.com/nabeek/Earthquake-Now/files/4431975/Earthquake.Now.pdf)
https://www.figma.com/file/BNysHYnPLJhbfSxRjwRVN1/Earthquake-Now?node-id=0%3A1

**Comment by shiftymitch** [comment]
Closed issue, #9
