### ISSUE TITLE
Fix News search parameter to work with "City, State" search input.

### ISSUE THREAD

**Issue by shiftymitch** [nabeek/Earthquake-Now#54]
Currently, it only works with a city name only. I'm assuming it's to do with the comma separator. Going to try altering the searchInputTerm when I store it to a new variable to get everything before the comma.

**Comment by shiftymitch** [comment]
Actually, it looks like the issue is to do with abbreviated state names. Maybe we find a solution to convert abbreviated states to the full state name?

**Comment by nabeek** [comment]
I found an easy solution while looking around this afternoon. We can clone the js file and credit the author in our README: https://github.com/TexasSwede/stateAbbreviations

**Comment by shiftymitch** [comment]
Closed issue, #71
