### ISSUE TITLE
Add attribution reference for NewsAPI

### ISSUE THREAD

**Issue by nabeek** [nabeek/Earthquake-Now#6]

**Comment by nabeek** [comment]
The NewsAPI site says "a mention in your Github repo" in sufficient for the attribution, so I think we add it to our README

**Comment by nvalline** [comment]
We'll put it in the References section of the README

**Comment by nvalline** [comment]
Do you have the info that needs to be displayed?

**Comment by nabeek** [comment]
Closed by @nvalline via #84
